<?php
session_start();
include('includes/config.php');
require_once('../tcpdf/tcpdf.php');

// Create new PDF document
$pdf = new TCPDF('P', PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Library Management System');
$pdf->SetTitle('Books Listing');
$pdf->SetSubject('Books Listing');
$pdf->SetKeywords('TCPDF, PDF, books, library');

// Set default header data
$pdf->SetHeaderData('', 0, 'Books Listing', 'Generated by Library Management System');

// Set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Set font
$pdf->SetFont('helvetica', '', 10);

// Add a page
$pdf->AddPage();

// Add title
$pdf->SetFont('helvetica', 'B', 14);
$pdf->Cell(0, 10, 'Books Listing', 0, 1, 'C');
$pdf->Ln(5);

// Table header
$pdf->SetFont('helvetica', 'B', 10);
$pdf->Cell(10, 10, '#', 1, 0, 'C');
$pdf->Cell(50, 10, 'Book Name', 1, 0, 'C');
$pdf->Cell(40, 10, 'Category', 1, 0, 'C');
$pdf->Cell(40, 10, 'Author', 1, 0, 'C');
$pdf->Cell(30, 10, 'ISBN', 1, 0, 'C');
$pdf->Cell(20, 10, 'Price', 1, 1, 'C');

// Fetch data from database
$search = isset($_GET['search']) ? trim($_GET['search']) : '';

$sql = "SELECT tblbooks.BookName, tblcategory.CategoryName, tblauthors.AuthorName, tblbooks.ISBNNumber, tblbooks.BookPrice 
        FROM tblbooks 
        JOIN tblcategory ON tblcategory.id = tblbooks.CatId 
        JOIN tblauthors ON tblauthors.id = tblbooks.AuthorId";

if ($search !== '') {
    $sql .= " WHERE (tblbooks.BookName LIKE :search OR tblcategory.CategoryName LIKE :search OR tblauthors.AuthorName LIKE :search OR tblbooks.ISBNNumber LIKE :search OR tblbooks.BookPrice LIKE :search)";
}

$query = $dbh->prepare($sql);
if ($search !== '') {
    $like = "%$search%";
    $query->bindParam(':search', $like, PDO::PARAM_STR);
}
$query->execute();
$results = $query->fetchAll(PDO::FETCH_OBJ);

$cnt = 1;
$pdf->SetFont('helvetica', '', 10);
foreach ($results as $result) {
    $pdf->Cell(10, 10, $cnt, 1, 0, 'C');
    $pdf->Cell(50, 10, $result->BookName, 1, 0, 'L');
    $pdf->Cell(40, 10, $result->CategoryName, 1, 0, 'L');
    $pdf->Cell(40, 10, $result->AuthorName, 1, 0, 'L');
    $pdf->Cell(30, 10, $result->ISBNNumber, 1, 0, 'L');
    $pdf->Cell(20, 10, $result->BookPrice, 1, 1, 'R');
    $cnt++;
}

// Output PDF
$pdf->Output('Books_Listing.pdf', 'D');
?>