<?php
// filepath: c:\xampp\htdocs\library\admin\export-authors.php
require_once('../tcpdf/tcpdf.php');
require_once('includes/config.php');

// Create new PDF document
$pdf = new TCPDF('P', PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Online Library Management System');
$pdf->SetTitle('Authors Listing');
$pdf->SetSubject('Authors Listing');
$pdf->SetKeywords('TCPDF, PDF, Authors, Library');

// Set default header data
$pdf->SetHeaderData('', 0, 'Authors Listing', 'Generated by Online Library Management System');

// Set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Set font
$pdf->SetFont('helvetica', '', 12);

// Add a page
$pdf->AddPage();

// Fetch authors data from the database
$search = isset($_GET['search']) ? trim($_GET['search']) : '';

$sql = "SELECT * FROM tblauthors";
if ($search !== '') {
    $sql .= " WHERE AuthorName LIKE :search OR creationDate LIKE :search OR UpdationDate LIKE :search";
}

$query = $dbh->prepare($sql);
if ($search !== '') {
    $like = "%$search%";
    $query->bindParam(':search', $like, PDO::PARAM_STR);
}
$query->execute();
$results = $query->fetchAll(PDO::FETCH_OBJ);

// Create HTML content for the PDF
$html = '<h2>Authors Listing</h2>';
$html .= '<table border="1" cellpadding="5">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Author Name</th>
                    <th>Creation Date</th>
                    <th>Updation Date</th>
                </tr>
            </thead>
            <tbody>';

$cnt = 1;
if ($query->rowCount() > 0) {
    foreach ($results as $result) {
        $html .= '<tr>
                    <td>' . $cnt . '</td>
                    <td>' . htmlentities($result->AuthorName) . '</td>
                    <td>' . htmlentities($result->creationDate) . '</td>
                    <td>' . htmlentities($result->UpdationDate) . '</td>
                  </tr>';
        $cnt++;
    }
} else {
    $html .= '<tr><td colspan="4">No records found</td></tr>';
}

$html .= '</tbody></table>';

// Output the HTML content to the PDF
$pdf->writeHTML($html, true, false, true, false, '');

// Close and output PDF document
$pdf->Output('Authors_Listing.pdf', 'D');
?>